version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: api_app
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
        - "5000:80"
    depends_on:
        - sql_db

  sql_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_db
    user: root
    environment:
        - ACCEPT_EULA=y
        - MSSQL_SA_PASSWORD=AVeryComplex123Password
        - MSSQL_PID=Express
    volumes:
        - data:/var/opt/mssql/data

volumes:
  data: