version: "3.9"

services:
  authorization:
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
      ASPNETCORE_URLS: https://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: ComplexPassword
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/authorizationpassword.pfx
    ports:
      - 5000:80
    volumes:
      - ./AuthorizationService/.aspnet/https:/https:ro
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: "LifeCreatorDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - authorization_data:/var/lib/postgresql/data

volumes:
  authorization_data:
  core_data:  